name = "Forgeworks"
author = "Jaron Zijlstra"
version = "1.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2c2913487ec16c3dce4795bc9e534613f771dc8fddc8f65a20839bb3aa5552e"

[versions]
fabric = "0.16.4"
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21.1"]
