name = "Forgeworks"
author = "Jaron Zijlstra"
version = "1.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c114786d47e960a7fbda7664e9bb331d26a64dd2db63ef60100e9e8f8d6f33e"

[versions]
fabric = "0.16.4"
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21.1"]
