name = "Forgeworks"
author = "Jaron Zijlstra"
version = "1.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ca5a36312ce73e5f3d18e4be90a4ae62849e7444c820e0e2887eb74a14d1674"

[versions]
fabric = "0.16.4"
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21.1"]
