name = "Forgeworks"
author = "Jaron Zijlstra"
version = "1.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d3ddbb0d8a6a422629a9085c9f9360ba5c5550ee4dc3c603e4265d2a1eae503"

[versions]
fabric = "0.16.4"
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21.1"]
