name = "Forgeworks"
author = "Jaron Zijlstra"
version = "1.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb73c7269f6f094c52dd3462239efd15106bc5085b1250327cc2ee78f150b5cf"

[versions]
fabric = "0.16.4"
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21.1"]
