name = "Forgeworks"
author = "Jaron Zijlstra"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93e2b425afd4cc1c3ec828d5549d84812ee921bc1ee576f5c6e31accdd53ac80"

[versions]
fabric = "0.16.4"
minecraft = "1.21.1"
neoforge = "21.1.200"

[options]
acceptable-game-versions = ["1.21.1"]
