name = "Forgeworks"
author = "Jaron Zijlstra"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9f506de2d6cfd2847d0190567bf9944a1cb3a721b479c0a0bbe4bf91dee073f"

[versions]
fabric = "0.16.4"
minecraft = "1.21.1"
neoforge = "21.1.173"

[options]
acceptable-game-versions = ["1.21.1"]
