name = "Forgeworks"
author = "Jaron Zijlstra"
version = "1.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bab20e4d62e4eba4f63abb3b8973a152cf8b65fef9c516343a5c4e73fb1f13d5"

[versions]
fabric = "0.16.4"
minecraft = "1.21.1"
neoforge = "21.1.210"

[options]
acceptable-game-versions = ["1.21.1"]
