name = "Forgeworks"
author = "Jaron Zijlstra"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc5d66abcf6bd9323153fa13dbf744f6e1e0f6db9ecbf7d43a4e289f6a0ca5c9"

[versions]
fabric = "0.16.4"
minecraft = "1.21.1"
neoforge = "21.1.200"

[options]
acceptable-game-versions = ["1.21.1"]
