name = "Forgeworks"
author = "Jaron Zijlstra"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "310f8dd5a01fc9383b31a90889241e4593d4b227a1274380356e469a86de0ad5"

[versions]
fabric = "0.16.4"
minecraft = "1.21.1"
neoforge = "21.1.200"

[options]
acceptable-game-versions = ["1.21.1"]
