blank_issues_enabled: true
contact_links:
  - name: Contact Support
    url: https://discord.com/users/472312270047674378
    about: Send me a message in discord for support.
  - name: CurseForge
    url: https://www.curseforge.com/minecraft/modpacks/forgeworks/comments
    about: Add a comment to the Forgeworks modpack in CurseForge.