name: Publish
run-name: Publish ${{ inputs.package }}

on:
  workflow_dispatch:
    inputs:
      package:
        description: The package to publish
        required: true
        type: choice
        options:
          - forgeworks
          - minigames
      skip-automatic-bump:
        description: Whether to skip the automatic bumping of the package version
        required: false
        default: false
        type: boolean

jobs:
  ExportPackage:
    name: Export ${{ inputs.package }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Install Dependencies
        uses: ./.github/actions/install-yarn-dependencies
        with:
          node-version: 22
      - name: Install nix
        uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641 # v31
      - name: Build Package
        run: yarn build
      - name: Export CurseForge Package
        working-directory: packages/${{ inputs.package }}
        run: |
          mkdir -p export
          yarn ci:curseforge:export
      - name: Upload Exported Packages
        uses: actions/upload-artifact@v4
        with:
          name: export
          path: packages/${{ inputs.package }}/export/

  PublishPackage:
    name: Publish ${{ inputs.package }}
    runs-on: ubuntu-latest
    needs: ExportPackage
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Create App Token
        uses: actions/create-github-app-token@v2
        id: create-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ steps.create-token.outputs.token }}
      - name: Download Exported Packages
        uses: actions/download-artifact@v5
        with:
          name: export
          path: ./export/
      - name: Install Dependencies
        uses: ./.github/actions/install-yarn-dependencies
        with:
          node-version: 22
      - name: Configure Git
        run: |
          git config --local user.email "${GITHUB_EMAIL}"
          git config --local user.name "${GITHUB_USER}"
        env:
          GITHUB_USER: jaronz-ci[bot]
          GITHUB_EMAIL: 227836284+jaronz-ci[bot]@users.noreply.github.com
      - name: Bump Versions and make release
        working-directory: packages/${{ inputs.package }}
        run: |
          if [ "${{ inputs.skip-automatic-bump }}" = "true" ]; then
            yarn bump --skip-automatic-bump
          else
            yarn bump
          fi
        env:
          GITHUB_TOKEN: ${{ steps.create-token.outputs.token }}
      - name: Upload Exported Packages
        run: |
          tag=$(gh release view --json tagName -q .tagName)
          gh release upload "$tag" export/curseforge.zip
        env:
          GITHUB_TOKEN: ${{ steps.create-token.outputs.token }}
